'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, BarChart3, Check, ChevronDown, CircleCheck, Code2, Fingerprint, Github, KeyRound, LockKeyhole, Menu, Network, Search, Shield, ShieldCheck, Sparkles, UserRound, Users, X, Zap } from 'lucide-react'

const nav = [['Product', 'features'], ['Security', 'security'], ['How it works', 'process'], ['Pricing', 'pricing'], ['Documentation', 'docs']]
const faqs = [
 ['How quickly can we integrate AuthGuard?', 'Most teams complete their first email and password flow in under five minutes using our SDKs and guided setup. Complex migrations can be rolled out gradually.'],
 ['Can we migrate existing users?', 'Yes. Import users in bulk, preserve profile metadata, and use a staged password migration so customers do not need to reset credentials all at once.'],
 ['Which login methods are supported?', 'Email and password, magic links, social OAuth, SMS access, multifactor authentication, and enterprise SSO are supported by plan.'],
 ['How is account data protected?', 'AuthGuard uses encrypted transport and storage, short lived sessions, audit trails, rate limiting, and configurable access policies.'],
]

export default function Home() {
 const [open,setOpen]=useState(false), [annual,setAnnual]=useState(true), [faq,setFaq]=useState<number|null>(0), [quote,setQuote]=useState(0)
 return <main className="overflow-hidden bg-brand-bg text-brand-text">
  <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo/><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 lg:flex">{nav.map(([l,id])=><a key={id} href={`#${id}`} className="transition hover:text-brand">{l}</a>)}</nav><div className="hidden items-center gap-3 lg:flex"><Link href="/login" className="px-3 py-2 text-sm font-semibold">Sign in</Link><Link href="/register" className="rounded-md bg-brand px-4 py-2.5 text-sm font-semibold text-white">Start free trial</Link></div><button aria-label="Toggle navigation" onClick={()=>setOpen(!open)} className="rounded-md p-2 lg:hidden">{open?<X/>:<Menu/>}</button></div>
   <div className={`absolute left-0 right-0 border-b bg-white px-5 py-5 shadow-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] lg:hidden ${open?'pointer-events-auto translate-y-0 opacity-100':'pointer-events-none -translate-y-4 opacity-0'}`}>{nav.map(([l,id],i)=><a onClick={()=>setOpen(false)} style={{transitionDelay:open?`${i*60}ms`:'0ms'}} className="block border-b py-3 text-sm font-semibold transition-all" key={id} href={`#${id}`}>{l}</a>)}<div className="mt-4 grid grid-cols-2 gap-3"><Link href="/login" className="rounded-md border px-4 py-3 text-center text-sm font-semibold">Sign in</Link><Link href="/register" className="rounded-md bg-brand px-4 py-3 text-center text-sm font-semibold text-white">Start free trial</Link></div></div></header>

  <section className="relative border-b bg-grid"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_30%,rgba(0,82,204,.13),transparent_32%)]"/><div className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-14 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-800"><Sparkles size={14}/> Authentication infrastructure for modern teams</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.05] tracking-[-.045em] sm:text-6xl">Secure authentication, <span className="text-brand">built for speed.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Deploy user registration and login in under 5 minutes. Enterprise security, zero complexity.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-md bg-brand px-5 py-3.5 font-semibold text-white shadow-lg shadow-blue-900/15">Start free trial <ArrowRight size={18}/></Link><a href="#docs" className="inline-flex items-center justify-center gap-2 rounded-md border bg-white px-5 py-3.5 font-semibold"><Code2 size={18}/> View documentation</a></div><p className="mt-5 flex items-center gap-2 text-sm text-slate-500"><CircleCheck size={16} className="text-emerald-500"/> No credit card required · Launch your first flow today</p></div><AuthMockup/></div></section>
  <section aria-label="Trust metrics" className="border-b bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-y px-5 sm:grid-cols-3 lg:grid-cols-5 lg:divide-y-0 lg:px-8">{[['250,000+','users managed daily'],['99.9%','uptime SLA'],['ISO 27001','certified'],['< 200ms','login latency'],['GDPR & CCPA','compliant']].map(([n,l])=><div className="px-4 py-7 text-center" key={l}><strong className="block text-lg">{n}</strong><span className="text-xs text-slate-500">{l}</span></div>)}</div></section>

  <section id="features" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHead eyebrow="One secure layer" title="Everything you need to manage users" text="Composed primitives and sensible defaults give your team control without slowing down product delivery."/><div className="mt-12 grid gap-5 lg:grid-cols-6">
   <Feature className="lg:col-span-4" icon={<LockKeyhole/>} title="Secure registration" text="Email verification, password strength enforcement, CAPTCHA integration, and duplicate prevention built in."><PasswordPreview/></Feature>
   <Feature className="bg-slate-950 text-white lg:col-span-2" icon={<KeyRound/>} title="Flexible login options" text="Give every customer the right way in, from email to passwordless access."><div className="mt-7 space-y-3"><Mini icon={<Github/>} text="Continue with GitHub"/><Mini icon={<Fingerprint/>} text="Use a passkey"/><Mini icon={<Zap/>} text="Send a magic link"/></div></Feature>
   <Feature className="lg:col-span-2" icon={<UserRound/>} title="Profile management" text="Editable fields, session control, activity logs, and role based permissions."><div className="mt-7 flex items-center gap-3 rounded-md border bg-slate-50 p-4"><span className="grid size-10 place-items-center rounded-full bg-blue-100 font-bold text-brand">AL</span><div><b className="block text-sm">Alex Lee</b><span className="text-xs text-slate-500">Workspace admin</span></div><CircleCheck className="ml-auto text-emerald-500" size={18}/></div></Feature>
   <Feature className="lg:col-span-4" icon={<BarChart3/>} title="One dashboard, complete visibility" text="Monitor active users, connected apps, sessions, roles, and security events from a single operational view."><ActivityChart/></Feature>
  </div></section>

  <section id="process" className="border-y bg-white px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHead eyebrow="Simple by design" title="From signup to trusted session" text="A clear, secure path for every user and every team."/><div className="relative mt-14 grid gap-6 md:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-6 hidden h-px bg-blue-200 md:block"/>{[['01','Sign up','Real time password checks'],['02','Email verification','One click confirmation'],['03','Dashboard access','Personalized account summary'],['04','Manage anytime','Sessions, apps, and MFA']].map(([n,t,d],i)=><div className="relative" key={t}><span className="relative z-10 grid size-12 place-items-center rounded-full border-4 border-white bg-brand text-sm font-bold text-white">{n}</span><div className="mt-5 rounded-md border bg-brand-bg p-5"><div className="mb-5 h-20 rounded border bg-white p-3"><div className="mb-2 h-2 w-2/3 rounded bg-slate-200"/><div className="h-2 rounded bg-blue-100" style={{width:`${55+i*12}%`}}/><div className="mt-3 flex gap-1">{[1,2,3].map(x=><span key={x} className={`h-1.5 flex-1 rounded ${x<=i+1?'bg-emerald-400':'bg-slate-200'}`}/>)}</div></div><h3 className="font-bold">{t}</h3><p className="mt-1 text-sm text-slate-500">{d}</p></div></div>)}</div></div></section>

  <section id="security" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><span className="eyebrow">Security without compromise</span><h2 className="mt-4 text-4xl font-bold tracking-tight">Enterprise security out of the box.</h2><p className="mt-5 leading-7 text-slate-600">Layered safeguards protect identities from the first request to every active session.</p><a href="#pricing" className="mt-7 inline-flex items-center gap-2 font-semibold text-brand">Explore plans <ArrowRight size={17}/></a></div><div className="space-y-4">{[[Shield,'Encryption at rest and transit','AES 256 encryption, TLS 1.3 transport, encrypted backups, and isolated key management.'],[Search,'Compliance and auditing','SOC 2 Type II controls, GDPR ready workflows, auth event logs, and data residency options.'],[Network,'DDoS and threat protection','Rate limits, IP policies, suspicious login detection, and automated account lockouts.']].map(([I,t,d])=>{const Icon=I as typeof Shield;return <div key={t as string} className="grid gap-4 rounded-md border bg-white p-6 sm:grid-cols-[48px_1fr]"><span className="grid size-12 place-items-center rounded-md bg-blue-50 text-brand"><Icon/></span><div><h3 className="text-lg font-bold">{t as string}</h3><p className="mt-2 leading-7 text-slate-600">{d as string}</p></div></div>})}</div></div></section>

  <section className="bg-slate-950 px-5 py-24 text-white"><div className="mx-auto max-w-5xl"><div className="flex items-end justify-between"><div><span className="eyebrow text-blue-300">Trusted by growing teams</span><h2 className="mt-4 text-4xl font-bold">Auth that lets teams move.</h2></div><div className="hidden gap-2 sm:flex"><button aria-label="Previous testimonial" onClick={()=>setQuote((quote+2)%3)} className="rounded-md border border-white/20 p-3">←</button><button aria-label="Next testimonial" onClick={()=>setQuote((quote+1)%3)} className="rounded-md border border-white/20 p-3">→</button></div></div><div className="mt-12 rounded-md border border-white/10 bg-white/[.06] p-8 sm:p-12"><p className="text-2xl font-medium leading-10">“{['AuthGuard cut our auth implementation from 6 weeks to 3 days. The API docs are phenomenal.','We manage 40,000 users and have zero security incidents since switching. Peace of mind is priceless.','Support responds in minutes, not hours. We completed our switch within a month.'][quote]}”</p><div className="mt-8 flex items-center gap-4"><span className="grid size-11 place-items-center rounded-full bg-brand font-bold">{['SC','MR','JP'][quote]}</span><div><b className="block">{['Sarah Chen','Marcus Rodriguez','Jamie Patel'][quote]}</b><span className="text-sm text-slate-400">{['Lead Engineer, Velocity','CTO, Pixel Labs','Product Manager, StreamBox'][quote]}</span></div></div></div></div></section>

  <section id="pricing" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHead eyebrow="Transparent pricing" title="Start small. Scale securely." text="Every plan includes secure sessions, developer SDKs, and a managed user directory."/><div className="mx-auto mt-8 flex w-fit items-center rounded-md border bg-white p-1 text-sm"><button onClick={()=>setAnnual(false)} className={`rounded px-4 py-2 ${!annual?'bg-slate-900 text-white':''}`}>Monthly</button><button onClick={()=>setAnnual(true)} className={`rounded px-4 py-2 ${annual?'bg-slate-900 text-white':''}`}>Annual <span className="text-emerald-400">save 20%</span></button></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><Price name="Starter" price={annual?'$23':'$29'} desc="For early products proving demand." items={['Up to 5,000 users','Email and password auth','Basic profile management','Community support','99.5% uptime SLA']}/><Price featured name="Professional" price={annual?'$79':'$99'} desc="For growing teams with complex flows." items={['Up to 50,000 users','OAuth and passwordless','Advanced profile fields','Email support','99.9% uptime SLA','Audit logs']}/><Price name="Enterprise" price="Custom" desc="For organizations requiring control." items={['Unlimited users','SSO and SAML','Custom branding','Dedicated account manager','24/7 priority support','Advanced fraud detection']}/></div></section>

  <section id="docs" className="border-y bg-white px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><span className="eyebrow">Built for developers</span><h2 className="mt-4 text-3xl font-bold">One clear API. Every auth flow.</h2><p className="mt-4 text-slate-600">Searchable guides, typed SDKs, tested examples, and integration paths for the tools you already use.</p><Link href="/register" className="mt-7 inline-flex items-center gap-2 font-semibold text-brand">Get your API keys <ArrowRight size={17}/></Link></div><div className="overflow-hidden rounded-md border bg-slate-950"><div className="border-b border-white/10 px-4 py-3 text-xs text-slate-500">quickstart.ts</div><pre className="overflow-x-auto p-6 text-sm leading-7 text-blue-200"><code>{`import { AuthGuard } from '@authguard/sdk'\n\nconst auth = new AuthGuard({ apiKey })\n\nconst session = await auth.signIn({\n  email, password\n})`}</code></pre></div></div></section>
  <section className="mx-auto max-w-4xl px-5 py-24"><SectionHead eyebrow="Questions, answered" title="Everything you need to know"/><div className="mt-10 divide-y border-y">{faqs.map(([q,a],i)=><div key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} className="flex w-full items-center justify-between py-5 text-left font-semibold">{q}<ChevronDown className={`transition ${faq===i?'rotate-180':''}`}/></button><div className={`grid transition-all duration-300 ${faq===i?'grid-rows-[1fr] pb-5':'grid-rows-[0fr]'}`}><p className="overflow-hidden leading-7 text-slate-600">{a}</p></div></div>)}</div></section>
  <section className="px-5 pb-8 lg:px-8"><div className="mx-auto max-w-7xl rounded-md bg-brand px-6 py-16 text-center text-white"><h2 className="text-4xl font-bold">Your users are ready. Are you?</h2><p className="mx-auto mt-4 max-w-xl text-blue-100">Build your first secure authentication flow today. No credit card, no infrastructure work.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/register" className="rounded-md bg-white px-6 py-3.5 font-semibold text-brand">Start free trial</Link><a href="#docs" className="rounded-md border border-white/30 px-6 py-3.5 font-semibold">Read the docs</a></div></div></section><Footer/>
 </main>
}

function Logo(){return <Link href="/" className="flex items-center gap-2 font-bold"><span className="grid size-8 place-items-center rounded-md bg-brand text-white"><ShieldCheck size={18}/></span>AuthGuard</Link>}
function SectionHead({eyebrow,title,text}:{eyebrow:string,title:string,text?:string}){return <div className="mx-auto max-w-2xl text-center"><span className="eyebrow">{eyebrow}</span><h2 className="mt-4 text-4xl font-bold tracking-[-.03em]">{title}</h2>{text&&<p className="mt-4 leading-7 text-slate-600">{text}</p>}</div>}
function Feature({icon,title,text,children,className=''}:{icon:React.ReactNode,title:string,text:string,children:React.ReactNode,className?:string}){return <article className={`rounded-md border bg-white p-7 shadow-sm ${className}`}><span className="grid size-11 place-items-center rounded-md bg-blue-50 text-brand">{icon}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className={`mt-2 max-w-xl leading-7 ${className.includes('text-white')?'text-slate-400':'text-slate-600'}`}>{text}</p>{children}</article>}
function Mini({icon,text}:{icon:React.ReactNode,text:string}){return <div className="flex items-center gap-3 rounded-md border border-white/10 bg-white/5 p-3 text-sm"><span className="text-blue-300">{icon}</span>{text}</div>}
function PasswordPreview(){return <div className="mt-7 rounded-md border bg-slate-50 p-4"><div className="flex justify-between text-xs font-medium"><span>Password strength</span><span className="text-emerald-600">Strong</span></div><div className="mt-3 flex gap-1">{[1,2,3,4].map(i=><i key={i} className="h-1.5 flex-1 rounded bg-emerald-500"/>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{['12 characters minimum','One uppercase letter','One number','No exposed passwords'].map(x=><span key={x} className="flex items-center gap-2 text-xs text-slate-500"><Check size={13} className="text-emerald-500"/>{x}</span>)}</div></div>}
function ActivityChart(){return <div className="mt-7 grid h-40 grid-cols-8 items-end gap-2 rounded-md border bg-slate-50 p-5">{[42,68,51,78,63,91,74,96].map((n,i)=><div key={i} className="rounded-t bg-blue-500/80" style={{height:`${n}%`}}/>)}</div>}
function AuthMockup(){return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 rounded-full bg-blue-200/50 blur-3xl"/><div className="relative overflow-hidden rounded-xl border bg-white shadow-2xl"><div className="flex h-11 items-center gap-2 border-b px-4"><i className="size-2.5 rounded-full bg-red-400"/><i className="size-2.5 rounded-full bg-amber-400"/><i className="size-2.5 rounded-full bg-emerald-400"/><span className="mx-auto rounded bg-slate-100 px-12 py-1 text-[10px] text-slate-400">app.authguard.dev</span></div><div className="grid min-h-[410px] sm:grid-cols-[150px_1fr]"><aside className="hidden border-r bg-slate-950 p-4 text-slate-400 sm:block"><b className="mb-8 flex gap-2 text-xs text-white"><ShieldCheck size={16}/> AuthGuard</b>{['Overview','Users','Sessions','Events'].map((x,i)=><div className={`mb-3 flex items-center gap-2 rounded p-2 text-[10px] ${i===1?'bg-white/10 text-white':''}`} key={x}><Users size={13}/>{x}</div>)}</aside><div className="bg-slate-50 p-5"><div className="mb-5"><span className="text-[10px] text-slate-400">Welcome back</span><h3 className="text-sm font-bold">Authentication overview</h3></div><div className="grid grid-cols-2 gap-3"><Metric n="12,842" t="Active users"/><Metric n="99.99%" t="Success rate"/></div><div className="mt-3 rounded-md border bg-white p-4"><div className="flex justify-between text-[10px]"><b>Sign in activity</b><span>Last 7 days</span></div><div className="mt-5 flex h-24 items-end gap-2">{[45,61,54,76,67,82,95,78,88,91].map((h,i)=><i key={i} className="flex-1 rounded-t bg-brand/80" style={{height:`${h}%`}}/>)}</div></div><div className="mt-3 flex items-center gap-3 rounded-md border bg-white p-3"><span className="grid size-8 place-items-center rounded-full bg-blue-100 text-[10px] font-bold text-brand">JL</span><div><b className="block text-[10px]">Jordan Lee signed in</b><span className="text-[9px] text-slate-400">Passkey · just now</span></div><CircleCheck className="ml-auto text-emerald-500" size={15}/></div></div></div></div></div>}
function Metric({n,t}:{n:string,t:string}){return <div className="rounded-md border bg-white p-3"><strong className="block text-lg">{n}</strong><span className="text-[9px] text-slate-400">{t}</span></div>}
function Price({name,price,desc,items,featured=false}:{name:string,price:string,desc:string,items:string[],featured?:boolean}){return <article className={`relative rounded-md border p-7 ${featured?'border-brand bg-white shadow-2xl ring-1 ring-brand':'bg-white'}`}>{featured&&<span className="absolute right-5 top-0 -translate-y-1/2 rounded-full bg-brand px-3 py-1 text-xs font-semibold text-white">Most popular</span>}<h3 className="text-lg font-bold">{name}</h3><p className="mt-2 min-h-12 text-sm text-slate-500">{desc}</p><div className="my-6"><strong className="text-4xl">{price}</strong>{price.startsWith('$')&&<span className="text-slate-500"> / month</span>}</div><Link href={name==='Enterprise'?'/contact':'/register'} className={`block rounded-md py-3 text-center font-semibold ${featured?'bg-brand text-white':'border'}`}>{name==='Enterprise'?'Talk to sales':'Start free trial'}</Link><ul className="mt-7 space-y-3 text-sm">{items.map(x=><li key={x} className="flex gap-2"><Check size={16} className="shrink-0 text-emerald-500"/>{x}</li>)}</ul></article>}
function Footer(){return <footer className="border-t bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-5 lg:px-8"><div className="sm:col-span-2"><Logo/><p className="mt-4 max-w-sm text-sm text-slate-500">Secure authentication infrastructure for teams building trusted digital products.</p></div>{[['Product','Features','Security','Pricing'],['Developers','Documentation','API reference','Status'],['Company','Contact','Privacy','Terms']].map(([h,...ls])=><div key={h}><b className="text-sm">{h}</b><ul className="mt-4 space-y-3 text-sm text-slate-500">{ls.map(l=><li key={l}><a href={l==='Contact'?'/contact':l==='Pricing'?'#pricing':l==='Features'?'#features':l==='Security'?'#security':'#docs'}>{l}</a></li>)}</ul></div>)}</div><div className="border-t px-5 py-6 text-center text-xs text-slate-500">© 2026 AuthGuard. Secure by design.</div></footer>}
